apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-service-data
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany 
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 5010
    targetPort: 80
  selector:
    web-service: webapp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-service
spec:
  selector:
    matchLabels:
      web-service: webapp
  template:
    metadata:
      labels:
        web-service: webapp
        system: server
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                web-service: webapp
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: webapp-service
        image: stefantestdocker/interpol-webapp-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: ApplicationSettings__Secret
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-secret
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: webapp-service-connection-string
        volumeMounts:
        - name: webapp-service-data
          mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
      - name: webapp-service-data
        persistentVolumeClaim:
          claimName: webapp-service-data