apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-settings
data:
  event-bus-host: event-bus
  event-bus-user: rabbitmquser

---

apiVersion: v1
kind: Secret
metadata:
 name: environment-secrets
data:
 # security-token-secret: Z29zaG9PaGhvaGFzZERmZkdBU0RBU0RkZGQ= used for microservices app
 webapp-database-sa-password: bXlEYkNvbm4zY3QxMG5QYXNzdzByRCFA
 webapp-service-connection-string: U2VydmVyPXdlYmFwcC1kYXRhYmFzZTtEYXRhYmFzZT1JbnRlcnBvbFN5c3RlbTtVc2VyIElkPXNhOyBQYXNzd29yZD1teURiQ29ubjNjdDEwblBhc3N3MHJEIUA7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU=
 