apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-settings
data:
  seed-initial-data: "True"
  event-bus-host: event-bus
  event-bus-user: rabbitmq
  notifications-allowed-origins: http://34.29.66.72
  admin-identity-endpoint: http://identity-service:5000
  admin-drive-endpoint: http://drive-service:5002
  admin-statistics-endpoint: http://statistics-service:5004
  watchdog-identity-health: http://identity-service:5000/health
  watchdog-drive-health: http://drive-service:5002/health
  watchdog-statistics-health: http://statistics-service:5004/health
  watchdog-notifications-health: http://notifications-service:5008/health
  watchdog-admin-health: http://admin-client:5000/health

---

apiVersion: v1
kind: Secret
metadata:
 name: environment-secrets
data:
 identity-database-sa-password: aWRlbnRpdHlEYXRhYmFzZVBhc3N3b3JkMTIhQA==
 statistics-database-sa-password: c3RhdGlzdGljc0RhdGFiYXNlUGFzc3dvcmQxMiFA
 drive-database-sa-password: ZHJpdmVEYXRhYmFzZVBhc3N3b3JkMTIhQA==
 security-token-secret: Z29zaG9PaGhvaGFzZERmZkdBU0RBU0RkZGQ=
 identity-service-connection-string: U2VydmVyPWlkZW50aXR5LWRhdGFiYXNlO0RhdGFiYXNlPVRhc2tUcm9uaWNJZGVudGl0eTtVc2VyIElkPXNhOyBQYXNzd29yZD1pZGVudGl0eURhdGFiYXNlUGFzc3dvcmQxMiFAO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
 statistics-service-connection-string: U2VydmVyPXN0YXRpc3RpY3MtZGF0YWJhc2U7RGF0YWJhc2U9VGFza1Ryb25pY1N0YXRpc3RpY3M7VXNlciBJZD1zYTsgUGFzc3dvcmQ9c3RhdGlzdGljc0RhdGFiYXNlUGFzc3dvcmQxMiFAO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
 drive-service-connection-string: U2VydmVyPWRyaXZlLWRhdGFiYXNlO0RhdGFiYXNlPVRhc2tUcm9uaWNEcml2ZTtVc2VyIElkPXNhOyBQYXNzd29yZD1kcml2ZURhdGFiYXNlUGFzc3dvcmQxMiFAO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
 event-bus-password: cmFiYml0bXE=