---

apiVersion: v1
kind: Service
metadata:
  name: webapp-client
spec:
  type: LoadBalancer
  ports:
    - port: 5010
      targetPort: 80
  selector:
    web-client: webapp-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-client
spec:
  replicas: 2
  selector:
    matchLabels:
      web-client: webapp-client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # all pods should be available while updating
      maxSurge: 1 # updates 1 by 1
  template:
    metadata:
      labels:
        web-client: webapp-client
        system: client
    spec:
      terminationGracePeriodSeconds: 2
      containers:
        - name: webapp-client
          image: stefantestdocker/interpol-webapp-client:sha-223a8f9711408743fb2e657a14846389fea9db19
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: webapp-service-connection-string

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-autoscaler
  namespace: webapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-client
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20
