---

apiVersion: v1
kind: Service
metadata:
  name: webapp-client
spec:
  type: LoadBalancer
  ports:
    - port: 5010
      targetPort: 80
  selector:
    web-client: webapp-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-client
spec:
  replicas: 2
  selector:
    matchLabels:
      web-client: webapp-client
  template:
    metadata:
      labels:
        web-client: webapp-client
        system: client
    spec:
      containers:
        - name: webapp-client
          image: stefantestdocker/interpol-webapp-client:sha-65f00f33c3f1f902ee7a52d887779490da2dce3a
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: webapp-service-connection-string