name: Deployment-of-microservice-app

on: [push]
  # push:
  #   paths:
  #     - 'test**'
  #   branches:
  #     - 'feature/pipelines'
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:
  push-to-docker-hub:
    needs: [git-leaks]
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_NAMESPACE }}/${{ secrets.DOCKER_REPOSITORY }}
          tags: |
            type=sha,format=long
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./src
          file: ./src/InterpolSystem.Web/Dockerfile
          push: true
          tags: "latest"
          labels: ${{ steps.meta.outputs.labels }}

  trivy-vulnerability-scanner:
    needs: [push-to-docker-hub]
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.DOCKER_NAMESPACE }}/${{ secrets.DOCKER_REPOSITORY }}:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"